In [14]:
import pandas as pd
from sklearn.metrics import log_loss
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
train_file = "train.csv"
test_file = "test.csv"

In [2]:
data = pd.read_csv(filename, header=0)
data.head(5)

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
# https://stackoverflow.com/questions/27697766/understanding-min-df-and-max-df-in-scikit-countvectorizer
# Above reference is for understanding the parameters of tf-idf.

tf = TfidfVectorizer(analyzer='word',lowercase=True, min_df = 3,max_df = 0.9,
                     strip_accents='unicode', stop_words = 'english', sublinear_tf=1)

X =  tf.fit_transform(data["comment_text"])
print("The number of features after applying TF-IDF are:")
print(len(tf.get_feature_names()))
print("The shape of the data is:")
print(X.shape)
print("Ten sample features are:")
tf.get_feature_names()[:10]

The number of features after applying TF-IDF are:
52471
The shape of the data is:
(159571, 52471)
Ten sample features are:


['00',
 '000',
 '0000',
 '000000',
 '0000z',
 '0001',
 '0003',
 '000th',
 '001',
 '0015']

In [26]:
# Read the test file
test_data = pd.read_csv(test_file)
test_data.tail(5)

id                                       comment_text
153159  fffcd0960ee309b5  . \n i totally agree, this stuff is nothing bu...
153160  fffd7a9a6eb32c16  == Throw from out field to home plate. == \n\n...
153161  fffda9e8d6fafa9e  " \n\n == Okinotorishima categories == \n\n I ...
153162  fffe8f1340a79fc2  " \n\n == ""One of the founding nations of the...
153163  ffffce3fb183ee80  " \n :::Stop already. Your bullshit is not wel...

In [17]:
X_test = tf.transform(test_data["comment_text"])
print(X_test.shape)

(153164, 52471)


In [18]:
# Predictions for toxic  using Logistic
clf = LogisticRegression(C=4, dual=False)
toxic_labels = list(data["toxic"])
clf.fit(X, toxic_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(toxic_labels, ans_probs)))
accuracy = round(accuracy_score(toxic_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(toxic_labels, predictions)

/home/manoj/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Log Loss: 0.07356333255173401
Accuracy: 97.22


array([[143570,    707],
       [  3730,  11564]])

In [27]:
toxic_test = clf.predict_proba(X_test)

In [31]:
test_data["toxic"] = pd.Series(toxic_test[:,1])

In [13]:
# Predictions for toxic using RF
clf = RandomForestClassifier(n_estimators=100, max_depth=10,random_state=0)
toxic_labels = list(data["toxic"])
clf.fit(X, toxic_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(toxic_labels, ans_probs)))
accuracy = round(accuracy_score(toxic_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(toxic_labels, predictions)

Log Loss: 0.27844885164676864
Accuracy: 90.42


array([[144277,      0],
       [ 15294,      0]])

In [34]:
# Predictions for severe_toxic using Logistic Regression
clf = LogisticRegression(C=4, dual=False)
severe_toxic_labels = list(data["severe_toxic"])
clf.fit(X, severe_toxic_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(severe_toxic_labels, ans_probs)))
accuracy = round(accuracy_score(severe_toxic_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(severe_toxic_labels, predictions)

/home/manoj/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Log Loss: 0.017566363766751688
Accuracy: 99.23


array([[157738,    238],
       [   984,    611]])

In [35]:
severe_toxic_test = clf.predict_proba(X_test)

In [36]:
test_data["severe_toxic"] = pd.Series(severe_toxic_test[:,1])

In [126]:
# Predictions for severe_toxic using RF
clf = RandomForestClassifier(n_estimators=100, max_depth=10,random_state=0)
severe_toxic_labels = list(data["severe_toxic"])
clf.fit(X, severe_toxic_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(severe_toxic_labels, ans_probs)))
accuracy = round(accuracy_score(severe_toxic_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(severe_toxic_labels, predictions)

Log Loss: 0.05159095192567949
Accuracy: 99.0


array([[157976,      0],
       [  1591,      4]])

In [37]:
# Predictions for obscene using Logistic Regression
clf = LogisticRegression(C=4, dual=False)
obscene_labels = list(data["obscene"])
clf.fit(X, obscene_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(obscene_labels, ans_probs)))
accuracy = round(accuracy_score(obscene_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(obscene_labels, predictions)

/home/manoj/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Log Loss: 0.038072869566416034
Accuracy: 98.54


array([[150657,    465],
       [  1858,   6591]])

In [38]:
obscene_test = clf.predict_proba(X_test)

In [39]:
test_data["obscene"] = pd.Series(obscene_test[:,1])

In [127]:
# Predictions for obscene using RF
clf = RandomForestClassifier(n_estimators=100, max_depth=10,random_state=0)
obscene_labels = list(data["obscene"])
clf.fit(X, obscene_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(obscene_labels, ans_probs)))
accuracy = round(accuracy_score(obscene_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(obscene_labels, predictions)

Log Loss: 0.19378512867958314
Accuracy: 94.71


array([[151122,      0],
       [  8449,      0]])

In [40]:
# Predictions for threat using Logistic Regression
clf = LogisticRegression(C=4, dual=False)
threat_labels = list(data["threat"])
clf.fit(X, threat_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(threat_labels, ans_probs)))
accuracy = round(accuracy_score(threat_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(threat_labels, predictions)

/home/manoj/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Log Loss: 0.005575788258684488
Accuracy: 99.78


array([[159060,     33],
       [   315,    163]])

In [41]:
threat_test = clf.predict_proba(X_test)
test_data["threat"] = pd.Series(threat_test[:,1])

In [121]:
# Predictions for threat using RF
clf = RandomForestClassifier(n_estimators=100, max_depth=10,random_state=0)
threat_labels = list(data["threat"])
clf.fit(X, threat_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(threat_labels, ans_probs)))
accuracy = round(accuracy_score(threat_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(threat_labels, predictions)

Log Loss: 0.014052635577133358
Accuracy: 99.7


array([[159093,      0],
       [   478,      0]])

In [42]:
# Predictions for insult using Logistic Regression
clf = LogisticRegression(C=4, dual=False)
insult_labels = list(data["insult"])
clf.fit(X, insult_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(insult_labels, ans_probs)))
accuracy = round(accuracy_score(insult_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(insult_labels, predictions)

/home/manoj/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Log Loss: 0.05229479145080292
Accuracy: 97.94


array([[150949,    745],
       [  2545,   5332]])

In [43]:
insult_test = clf.predict_proba(X_test)
test_data["insult"] = pd.Series(insult_test[:,1])

In [114]:
# Predictions for insult using RF
clf = RandomForestClassifier(n_estimators=100, max_depth=10,random_state=0)
insult_labels = list(data["insult"])
clf.fit(X, insult_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(insult_labels, ans_probs)))
accuracy = round(accuracy_score(insult_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(insult_labels, predictions)

Log Loss: 0.13738832868214773
Accuracy: 95.13


array([[151691,      3],
       [  7772,    105]])

In [44]:
# Predictions for identity_hate using Logistic Regression
clf = LogisticRegression(C=4, dual=False)
identity_hate_labels = list(data["identity_hate"])
clf.fit(X, identity_hate_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(identity_hate_labels, ans_probs)))
accuracy = round(accuracy_score(identity_hate_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(identity_hate_labels, predictions)

/home/manoj/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Log Loss: 0.015235570257447479
Accuracy: 99.4


array([[158066,    100],
       [   863,    542]])

In [45]:
identity_hate_test = clf.predict_proba(X_test)
test_data["identity_hate"] = pd.Series(identity_hate_test[:,1])

In [115]:
# Predictions for identity_hate using RF
clf = RandomForestClassifier(n_estimators=100, max_depth=10,random_state=0)
identity_hate_labels = list(data["identity_hate"])
clf.fit(X, identity_hate_labels)
ans_probs = clf.predict_proba(X)
predictions = clf.predict(X)
print("Log Loss: "+str(log_loss(identity_hate_labels, ans_probs)))
accuracy = round(accuracy_score(identity_hate_labels, predictions) *100,2)
print("Accuracy: "+str(accuracy))
confusion_matrix(identity_hate_labels, predictions)

Log Loss: 0.03306074294729274
Accuracy: 99.12


array([[158166,      0],
       [  1405,      0]])

In [46]:
test_data

id                                       comment_text  \
0       00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...   
1       0000247867823ef7  == From RfC == \n\n The title is fine as it is...   
2       00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...   
3       00017563c3f7919a  :If you have a look back at the source, the in...   
4       00017695ad8997eb          I don't anonymously edit articles at all.   
5       0001ea8717f6de06  Thank you for understanding. I think very high...   
6       00024115d4cbde0f  Please do not add nonsense to Wikipedia. Such ...   
7       000247e83dcc1211                   :Dear god this site is horrible.   
8       00025358d4737918  " \n Only a fool can believe in such numbers. ...   
9       00026d1092fe71cc  == Double Redirects == \n\n When fixing double...   
10      0002eadc3b301559  I think its crap that the link to roggenbier i...   
11      0002f87b16116a7f  "::: Somebody will invariably try to add Relig...   
12      0003806b11932181  , 25 February 2010 (UTC) \n\n :::Looking it ov...   
13      0003e1cccfd5a40a  " \n\n It says it right there that it IS a typ...   
14      00059ace3e3e9a53  " \n\n == Before adding a new product to the l...   
15      000634272d0d44eb  ==Current Position== \n Anyone have confirmati...   
16      000663aff0fffc80                           this other one from 1897   
17      000689dd34e20979  == Reason for banning throwing == \n\n This ar...   
18      000834769115370c  :: Wallamoose was changing the cited material ...   
19      000844b52dee5f3f             |blocked]] from editing Wikipedia.   |   
20      00084da5d4ead7aa  ==Indefinitely blocked== \n I have indefinitel...   
21      00091c35fa9d0465  == Arabs are committing genocide in Iraq, but ...   
22      000968ce11f5ee34  Please stop. If you continue to vandalize Wiki...   
23      0009734200a85047  == Energy  == \n\n I have edited the introduct...   
24      00097b6214686db5  :yeah, thanks for reviving the tradition of pi...   
25      0009aef4bd9e1697  MLM Software,NBFC software,Non Banking Financi...   
26      000a02d807ae0254  @RedSlash, cut it short. If you have sources s...   
27      000a6c6d4e89b9bc  ==================== \n Deception is the way o...   
28      000bafe2080bba82  . \n\n           Jews are not a race because y...   
29      000bf0a9894b2807  :::If Ollie or others think that one list of t...   
...                  ...                                                ...   
153134  fff3ae2e177b6bb3  " \n\n == Same coffee shop? == \n\n My memory ...   
153135  fff4109e837f7acc  SO many things wrong with that viewpoint - fro...   
153136  fff4373a81ef9f2a  " \n\n Unless we have an article for some othe...   
153137  fff460574ddbcd80  Hannah and Maddie are soooooo awesome and are ...   
153138  fff4fc0a1555be5c  :::no problem, I tagged it and cleaned it out....   
153139  fff5b9bb944d634c  :PS I've just looked at the history of this ar...   
153140  fff5c4a77fe0c05f  "== Your edit to Maungaturoto == \n Please don...   
153141  fff5fb61bd637c82  :If you wish to contest the prod, please remov...   
153142  fff69311f306df44  Balancing the two approaches to psychiatry ( b...   
153143  fff6ad63666fb304                                 Ah, suck my balls.   
153144  fff7159b3ee95618  == Your name mentioned == \n Hi, I just though...   
153145  fff718ffe5f05559  I've just discovered yet another list: List of...   
153146  fff7fc22a0cdccd3  ==Wikiproject Video Games assessment== \n I do...   
153147  fff83b80284d8440  ::Consensus for ruining Wikipedia? I think tha...   
153148  fff8ef316d0c6990  == DAP ?  == \n\n What's point with DAP ?! Naz...   
153149  fff8f521a7dbcd47  shut down the mexican border withought looking...   
153150  fff8f64043129fa2  :Jerome, I see you never got around to this…! ...   
153151  fff9d70fe0722906  ==Lucky bastard== \n http://wikimediafoundatio...   
153152  fff9fa508f400ee6  ==WTF== \n It's no longer a redlink.  Now what

In [47]:
del test_data["comment_text"]

In [49]:
test_data.to_csv("submission_1.csv", index=False)